// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCElm7HqRk1kH07dMfbfmH0geQGKKI5I2g',
    appId: '1:745966462019:web:32f7174dd730224a6720f6',
    messagingSenderId: '745966462019',
    projectId: 'todo-listo-7b8a8',
    authDomain: 'todo-listo-7b8a8.firebaseapp.com',
    storageBucket: 'todo-listo-7b8a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-uS9ZDhSzXrjGXAXaNtzrWP7TQAnTZc',
    appId: '1:745966462019:android:8a3f223822ee6c806720f6',
    messagingSenderId: '745966462019',
    projectId: 'todo-listo-7b8a8',
    storageBucket: 'todo-listo-7b8a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9SrYuWwma1R0dxco-8wi9SVvBE8_Mpc',
    appId: '1:745966462019:ios:3de23929a19cfb266720f6',
    messagingSenderId: '745966462019',
    projectId: 'todo-listo-7b8a8',
    storageBucket: 'todo-listo-7b8a8.appspot.com',
    iosBundleId: 'Adriano.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ9SrYuWwma1R0dxco-8wi9SVvBE8_Mpc',
    appId: '1:745966462019:ios:3de23929a19cfb266720f6',
    messagingSenderId: '745966462019',
    projectId: 'todo-listo-7b8a8',
    storageBucket: 'todo-listo-7b8a8.appspot.com',
    iosBundleId: 'Adriano.example.todo',
  );
}
